version: "3.8"

services:
  db-pedido:
    image: postgres:16.2
    hostname: db-pedido
    container_name: "containerBancoDeDadosPedidos"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./scriptBancoDeDados:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'containerRabbitMQ'
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - db-pedido
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  app-pedido:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: app-sistema-pedido
    environment:
      POSTGRES_HOST: db-pedido:5432
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
    restart: always